apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-grpc
  name: deploy-grpc
  namespace: usactar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-grpc
  template:
    metadata:
      labels:
        app: deploy-grpc
    spec:
      containers:

      - image: danielalfaro1/servergrpc
        imagePullPolicy: Always
        name: grpc-server
        ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-grpc
  name: service-grpc
  namespace: usactar
spec:
  type: LoadBalancer
  ports:
    - name: service-grpc
      port: 50051
      protocol: TCP
  selector:
    app: deploy-grpc