apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-redis
  name: deploy-redis
  namespace: usactar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-redis
  template:
    metadata:
      labels:
        app: deploy-redis
    spec:
      containers:

      - image: redis:7.0.5
        imagePullPolicy: Always
        name: redisdb
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-redis
  name: service-redis
  namespace: usactar
spec:
  type: LoadBalancer
  ports:
    - name: service-redis
      port: 6379
      protocol: TCP
  selector:
    app: deploy-redis